services:
  app:
    build: !reset null
    image: ghcr.io/drewdah/heirloom-audio/app:latest

  whisper-worker:
    build: !reset null
    image: ghcr.io/drewdah/heirloom-audio/whisper-worker:latest

  redis:
    ports: !reset []
